# Custom Language File for Launcher Customizer

[ejs.app]
title = "아이리스 픽셀몬"

[ejs.landing]
mediaGitHubURL = "https://gitbook.irispixelmon.net"
mediaTwitterURL = "#"
mediaInstagramURL = "https://cafe.naver.com/pixelmongn"
mediaYouTubeURL = "https://www.youtube.com/channel/UC5a9tAljKNSADsh79Jn-3mg"
mediaDiscordURL = "https://dsc.gg/irispixelmon"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/irispixelmon"
supportLink = "https://github.com/CustomLauncherLab/irispixelmon/issues"

[ejs.welcome]
welcomeHeader = "아이리스 픽셀몬"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
